DROP FUNCTION IF EXISTS `FN_CHECK_ORDERNO` */;
DELIMITER $$

CREATE DEFINER=`root`@`localhost` FUNCTION `FN_CHECK_ORDERNO`(i_orderid INT) RETURNS tinyint(4)
BEGIN
             IF NOT EXISTS(SELECT ORDER_TRANSACTION.`ORDER_NO` FROM `ORDER_TRANSACTION` WHERE ORDER_NO=i_orderid) THEN 
             RETURN TRUE;
             ELSE
             RETURN FALSE;
             END IF;
    END */$$
DELIMITER ;