
DROP FUNCTION IF EXISTS `FN_CHECK_SEAT_AVAILABILITY` */;
DELIMITER $$

CREATE DEFINER=`root`@`localhost` FUNCTION `FN_CHECK_SEAT_AVAILABILITY`(i_seatno INT) RETURNS tinyint(4)
BEGIN
           IF (SELECT `SEAT_MASTER`.`SEAT_STATUS` FROM SEAT_MASTER WHERE SEAT_NO=i_seatno) = "Not Occupied" THEN
           RETURN TRUE;
           ELSE
           RETURN FALSE;
           END IF;
    END */$$
DELIMITER ;