 DROP FUNCTION IF EXISTS `FN_GET_PRICE_OF_FOOD` */;
DELIMITER $$

CREATE DEFINER=`root`@`localhost` FUNCTION `FN_GET_PRICE_OF_FOOD`(i_foodname VARCHAR(50)) RETURNS int(11)
BEGIN
    DECLARE price INT;
         SELECT `ITEM_PRICE`.`PRICE` INTO price FROM `ITEM_PRICE` WHERE PRICE=i_foodname LIMIT 1 ;
         RETURN price;
    END */$$
DELIMITER ;