DROP PROCEDURE IF EXISTS  `PR_CHECK_SERVICE` */;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `PR_CHECK_SERVICE`(OUT errMsg VARCHAR(50))
BEGIN
         
    IF (CURTIME() BETWEEN (SELECT `END_TIME` FROM `CATEGORY_MASTER` WHERE CATEGORY_MASTER.`ID`=1) AND (SELECT `START_TIME` FROM CATEGORY_MASTER WHERE CATEGORY_MASTER.`ID`=2)) THEN
       
       SET errMsg="No service";
   ELSEIF (CURTIME() BETWEEN (SELECT `END_TIME` FROM `CATEGORY_MASTER` WHERE CATEGORY_MASTER.`ID`=2) AND (SELECT `START_TIME` FROM CATEGORY_MASTER WHERE CATEGORY_MASTER.`ID`=3))  THEN 
       
       SET errMsg="No service";
       
    ELSEIF (CURTIME() > (SELECT `END_TIME` FROM CATEGORY_MASTER WHERE CATEGORY_MASTER.`ID`=3)) THEN
    
       SET errMsg="No service";
       
           ELSEIF (CURTIME() > (SELECT `END_TIME` FROM CATEGORY_MASTER WHERE CATEGORY_MASTER.`ID`=4)) THEN
    
       SET errMsg="No service";
       elseif (CURTIME() < (SELECT `START_TIME` from `CATEGORY_MASTER` where `CATEGORY_MASTER`.`ID`=1)) THEN
       
       set errMsg="No Service";
     END IF;         
    END */$$
DELIMITER ;