DROP PROCEDURE IF EXISTS  `PR_DISPLAY_ITEMS_SERVED_TIME` */;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `PR_DISPLAY_ITEMS_SERVED_TIME`()
BEGIN
              SELECT `ITEM_NAME` FROM `ITEM_MASTER` JOIN `CATEGORY_MASTER` ON `ITEM_MASTER`.`ITEM_CATEGORY_CODE` = `CATEGORY_MASTER`.`ID`
              WHERE CURTIME() BETWEEN `CATEGORY_MASTER`.`START_TIME` AND `CATEGORY_MASTER`.`END_TIME`;
    END */$$
DELIMITER ;